on:
  push:
    branches:
      - "main"

jobs:
  # Copy-paste this from jobs: test in test workflow
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12.x", "14.x", "16.x"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        if: ${{ matrix.node-version == '16.x' }}
        run: npm ci
      # For npm < 7, we need to install from scratch instead of using lockfile v2,
      # due to some issues with fsevents and jest-haste-map.
      # https://stackoverflow.com/questions/68021121/fsevents-not-accessible-from-jest-haste-map
      - name: Install dependencies (npm < 7)
        if: ${{ matrix.node-version == '12.x' || matrix.node-version == '14.x' }}
        run: |
          rm package-lock.json
          npm i --production=false
      - name: Run tests
        run: npm test -- --coverage
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Execute linter
        run: npm run lint
      - name: Build TypeScript
        run: npm run build
      - name: Build documentation
        run: npm run docs
  publish-npm:
    needs: [test-node, test-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Create nightly version
        run: npm --no-git-tag-version version 0.0.0-nightly-$(date +"%Y%m%d-%H%M%S")
      - name: Publish to npm
        run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-docs:
    needs: [test-node, test-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build-docs
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Build documentation
        run: npm run docs
      - name: Commit and push
        run: |
          git config --global user.name "charaverse"
          git config --global user.email "charaverse@users.noreply.github.com"
          git merge origin/main
          git commit -am "docs: build docs"
          git push
